### ISSUE TITLE
Requirements for IANA page

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#144]
Assuming that the final product of the registry is still an IANA page (and it appears that is the case), what requirements should we place upon it? E.g.

* URL
* Text at top of page
* Registry entries
* URL anchors
* XML format

I think it's reasonable to assume that IANA will product exactly one non-HTML format, and that will be XML; this is what they do for other registries, and we shouldn't expect a unicorn.

**Comment by dret** [comment]
i like unicorns! well, maybe we can set an example by being more explicit about whatever they produce. here's my unicorn wishlist:

* stable and human-readable URI with no extension: http://registry.iana.com/link-relations
* serving a human-readable document at that URI: http://registry.iana.com/link-relations serves HTML
* working and discoverable fragment identifiers that are equal to the registered names; those should identify the fragment of the page that contains the name entry: http://registry.iana.com/link-relations#start identifies the fragment that's about the "start" link relation type
* URI linking to the document that requested the registration (preferably to the fragment in there that is the actual registration template, if such a fragment is available and stable): http://registry.iana.com/link-relations#start should link to http://www.w3.org/TR/1999/REC-html401-19991224/types.html#h-6.12 (sadly, "start" has no fragment identifier in the HTML spec)
* link to discussion thread that requested, discussed, and resolved the registration request
* link to history of registry, in particular when entries get updated and the registration data changes; there should be a complete registry history, sorted by date of substantial changes, and one for each entry, sorted by date

maybe that's a fancy unicorn. but then again, implementing something like this really isn't that hard, and there is a large variety of solutions out there that would you allow to do it. it does not even has to be any dynamic code and database, all of this is perfectly doable with a bit of structured data and some relatively simple build process. you could easily build it in any language you'd prefer, be it XML, JSON, or RDF (or something else entirely). this could become the blueprint for the many other registries that probably could use a little data management and openness love.

**Comment by mnot** [comment]
> stable and human-readable URI with no extension: http://registry.iana.com/link-relations

👍🏼

> serving a human-readable document at that URI: http://registry.iana.com/link-relations serves HTML

👍🏼

> working and discoverable fragment identifiers that are equal to the registered names; those should identify the fragment of the page that contains the name entry: http://registry.iana.com/link-relations#start identifies the fragment that's about the "start" link relation type

👍🏼 (although some could be tricky, esp. if the more permissive rules in HTML5 are used)

> URI linking to the document that requested the registration (preferably to the fragment in there that is the actual registration template, if such a fragment is available and stable): http://registry.iana.com/link-relations#start should link to http://www.w3.org/TR/1999/REC-html401-19991224/types.html#h-6.12 (sadly, "start" has no fragment identifier in the HTML spec)

👍🏼

> link to discussion thread that requested, discussed, and resolved the registration request

Hmm. How about a link to a way to find that easily (e.g., github search of the issues list)?

> link to history of registry, in particular when entries get updated and the registration data changes; there should be a complete registry history, sorted by date of substantial changes, and one for each entry, sorted by date

I think that follows from the previous.

**Comment by dret** [comment]
On 2015-10-16 13:36, Mark Nottingham wrote:
>     link to discussion thread that requested, discussed, and resolved
>     the registration request
> Hmm. How about a link to a way to find that easily (e.g., github search
> of the issues list)?

not good enough, otherwise people might just add links to google search? 
it should be a link to a managed, persistent archive, with a controlled 
tagging/categorization strategy (email subjects or github issue/PRs 
would qualify). also, come to think of it, that archive also MUST 
support subscription, so that people interested in following ongoing 
discussions can subscribe and get notified.

>     link to history of registry, in particular when entries get updated
>     and the registration data changes; there should be a complete
>     registry history, sorted by date of substantial changes, and one for
>     each entry, sorted by date
> I think that follows from the previous.

i don't think so. for example, "next" at some point was RFC 5005, and 
for some (surprising) reason now is listed as HTML5. afaict, the RFC 
5005 history and discussion is completely lost in the current registry. 
what i'd like to see is:

- have a way to find out that "next" at some point was registered by RFC 
5005.

- have a way to find the discussion that was held when RFC 5005 was 
registering "next". that is probably a different "thread id" or PR than 
that of the later HTML5 "next" discussion.

**Comment by dret** [comment]
maybe some interesting data points from these long-running experiments of mine... i have tracked three (REST-relevant) registered concepts, which are link relation types, HTTP headers, and media types. https://github.com/dret/sedola/tree/master/IETF contains a set of service descriptions for IETF specs. for example, https://github.com/dret/sedola/blob/master/IETF/RFC/5005.xml represents the concepts registered by RFC 5005. all the service descriptions are then combined into the MD lists at https://github.com/dret/sedola/tree/master/MD, such as https://github.com/dret/sedola/blob/master/MD/linkrels.md for link relation types. this is not a complete solution, but with a bit of extra effort (better tracking and archiving the service descriptions, along with some metadata), this is actually not too far away from being a substantial improvement over IANA's current practice.
all of this was started as an effort to describe RESTful services. they will usually use existing concepts (such as existing HTTP header fields), and maybe invent some new ones that they need. with a framework like this, it is easy to describe the "service surface" in terms of the concepts that a consumer of a specific service needs to understand in order to understand the service itself. using this model for describing "just" specifications is a nice side-effect of the larger goal of describing any kind of service.

**Comment by elf-pavlik** [comment]
> Assuming that the final product of the registry is still an IANA page (and it appears that is the case), what requirements should we place upon it? E.g.

>URL
Text at top of page
Registry entries
URL anchors
XML format

@mnot since all the relations will still stay *describedby* a single page, I think answer to your question https://github.com/mnot/I-D/issues/144 may suggest *URL + '(/)#'* as prefix with relations themselves used as *URL anchors*

@timbl @kidehen maybe you could offer your expertise on this issue?

>I think it's reasonable to assume that IANA will product exactly one non-HTML format, and that will be XML; this is what they do for other registries, and we shouldn't expect a unicorn..

Maybe this canonical 'text/html' page hosted by IANA could include link rel="alternate" to other pages which *describe* those relations in 'text/turtle', 'application/ld+json', 'application/rdf+xml'. Possibly hosted in http://www.w3.org/or https://w3id.org/ namespaces and automatically generated from 'text/xml' page provided by IANA

@gkellogg @iherman would that address your needs captured in https://github.com/w3c/csvw/issues/297 ?

**Comment by asbjornu** [comment]
@mnot wrote:
> I think it's reasonable to assume that IANA will product exactly one non-HTML format, and that will be XML; this is what they do for other registries, and we shouldn't expect a unicorn.

Could you please provide a link to a discussion that has lead to the (repeated) conclusion that IANA and IETF should not host HTML documents? I'm completely unable to fathom the decision and would love some reasoning.

@elf-pavlik wrote:
> Maybe this canonical 'text/html' page hosted by IANA could include link rel="alternate" to other pages which describe those relations in 'text/turtle', 'application/ld+json', 'application/rdf+xml'. Possibly hosted in http://www.w3.org/ or https://w3id.org/ namespaces and automatically generated from 'text/xml' page provided by IANA (possibly using GRDDL?)

That would solve a lot of problems, but as I understand @mnot, there won't be a canonical `text/html` representation hosted by IANA; it will be in XML or `text/plain`. I guess the XML document can borrow `atom:link` and use `rel="alternate"` to reference other representations, but the best would be to have **one HTTP resource** that could be retrieved as `application/xml`, `text/html`, `text/turtle`, `application/ld+json`, `application/rdf+xml`, etc.

I understand from the discussion that this is wishing for unicorns, I just don't understand why. Why oh why! :smile:

When it comes to the registry requirements, I think @dret nails it.

**Comment by mnot** [comment]
@asbjornu read again -- they can and do host HTML; I said "exactly one **non-**HTML format" :)

**Comment by asbjornu** [comment]
@mnot Aha. Sorry; I probably got it mixed up with XML becoming the normative representation of RFC's, which you wrote elsewhere (on e-mail, I think).

**Comment by iherman** [comment]
> On 18 Oct 2015, at 11:18, elf Pavlik <notifications@github.com> wrote:
> 
> Assuming that the final product of the registry is still an IANA page (and it appears that is the case), what requirements should we place upon it? E.g.
> 
> URL
> Text at top of page
> Registry entries
> URL anchors
> XML format
> 
> @mnot since all the relations will still stay describedby a single page, I think answer to your question #144 may suggest URL + '(/)#' as prefix with relations themselves used as URL anchors
> 
> @timbl @kidehen maybe you could offer your expertise on this issue?
> 
> I think it's reasonable to assume that IANA will product exactly one non-HTML format, and that will be XML; this is what they do for other registries, and we shouldn't expect a unicorn..
> 
> Maybe this canonical 'text/html' page hosted by IANA could include link rel="alternate" to other pages which describe those relations in 'text/turtle', 'application/ld+json', 'application/rdf+xml'. Possibly hosted in http://www.w3.org/or https://w3id.org/ namespaces and automatically generated from 'text/xml' page provided by IANA
> 
> @gkellogg @iherman would that address your needs captured in w3c/csvw#297 ?
> 
Unfortunately (and this just underlines the urgency of solving this whole issue) the CSVW Working Group had to move on, because we plan to issue a Recommendation at the end of January. Ie, we had to close all technical issues quite some times ago. As a consequence, our only choice was to close that issue by exchanging the only 'rel' like property to a property in our own namespace. Ain't pretty, but there we go.

I also have to add one more comment to the general discussion (I must admit I did not follow it very closely): once everything is closed and finalized, ie, we get to a situation whereby the rel values can be expressed in a ``rel:XXX`` in an RDFa or JSON-LD CURIE (with a fixed ``rel`` value), then this ``rel`` should also be added to the [RDFa initial context](http://www.w3.org/2011/rdfa-context/rdfa-1.1) which would, eventually, be picked up by RDFa and JSON-LD processors, ie, users can use ``rel`` without an explicit definition. Because, at the moment, I maintain that initial context, you should ping me when it is all set up:-)

Cc: @gkellogg

**Comment by gkellogg** [comment]
JSON-LD does not use an implicit context, but it will be useful for people to add to their own definitions.

**Comment by elf-pavlik** [comment]
> I also have to add one more comment to the general discussion (I must admit I did not follow it very closely): once everything is closed and finalized, ie, we get to a situation whereby the rel values can be expressed in a ``rel:XXX`` in an RDFa or JSON-LD CURIE (with a fixed ``rel`` value), then this ``rel`` should also be added to the [RDFa initial context](http://www.w3.org/2011/rdfa-context/rdfa-1.1) which would, eventually, be picked up by RDFa and JSON-LD processors, ie, users can use ``rel`` without an explicit definition. Because, at the moment, I maintain that initial context, you should ping me when it is all set up:-)

@iherman I worry that using CURIE rel:XXX in RDFa may contribute to what @dret to my understanding sees as a concern. [HTML5 4.8 Links](http://www.w3.org/TR/html5/links.html) recommend using link relations without prefix as implicitly mapping to registered link relations, in case of HTML5 spec [delegating it to other than IANA registry](http://www.w3.org/TR/html5/links.html#other-link-types). Preferably let's not reopen this can of worms in this issue and preferably move eventual conversation about use of link relations in HTML and RDFa elsewhere! (even better IRL TPAC2015)

@gkellogg I would see useful to publish in an easy to discover way JSON-LD context which will have definitions like `"next": { "@type": "@id" }` for all the relations. Maybe simple link from IANA page would do?
`<link rel="alternate" type="application/ld+json" href="http://www.w3.org/ns/iana/link">`

In general to avoid mentioned by Mark unicorns, I would see it in place that W3C would need to take responsibility for generating and hosting RDF compatible files based on canonical HTML (or XML)  published by IANA and do all the magic by simply including relevant links to "follow one's nose" from discussed here canonical page hosted by IANA.

**Comment by elf-pavlik** [comment]
I just noticed that W3C provides namespaces for various HTTP terms
http://www.w3.org/TR/HTTP-in-RDF/#namespaces

And hosts documents which describe them in RDF

**Comment by iherman** [comment]
> On 25 Oct 2015, at 05:25, elf Pavlik <notifications@github.com> wrote:
> 
> I just noticed that W3C provides namespaces for various HTTP terms
> http://www.w3.org/TR/HTTP-in-RDF/#namespaces <http://www.w3.org/TR/HTTP-in-RDF/#namespaces>
> And hosts documents which describe them in RDF
> 
Well, yes, but it is just a Working Draft, and I am not sure it will be pursued until a Recommendations.

**Comment by mnot** [comment]
Discussed with @timbl at TPAC. My inclination is to specify:

* The Expert(s) will provide the registry data to IANA in a format that's negotiated by them (likely, the current XML).
* IANA will publish text (including links and other formatting) as directed by the Experts(s) on the HTML of the registry page
* IANA will generate HTML from that
* IANA will also publish the canonical format
* IANA will also publish other formats as requested by the Expert(s)
* IANA will emit HTTP headers for all of the resources above as requested by the Expert(s)

**Comment by dret** [comment]
On 2015-10-27 06:36, Mark Nottingham wrote:
> Discussed with @timbl <https://github.com/timbl> at TPAC. My inclination
> is to specify:
>   * The Expert(s) will provide the registry data to IANA in a format
>     that's negotiated by them (likely, the current XML).
>   * IANA will publish text (including links and other formatting) as
>     directed by the Experts(s) on the HTML of the registry page
>   * IANA will generate HTML from that

maybe i am not following this completely. there will be text and then 
HTML generated from that? frankly, i would not care so much about which 
representation the registry page has, as long as:

- there are working fragment identifiers into this page that effectively 
give all registry entries stable URI references (the 
registryURI#registryValue URI reference mentioned earlier).

- for each registry entry, there is a link to the discussion/thread that 
led to the creation of that entry.

and ideally, i'd like to add this:

- there is a registry history that allows people to see which entries 
where changed and when and why. this does not need to be a complete 
history, but some record of what happened would be great.

as mentioned earlier, 
https://github.com/dret/sedola/blob/master/MD/linkrels.md is one example 
of how this could look like (but it does not have the fragment 
identifiers because MD does not support them, so this would nee to be 
added).

https://github.com/dret/sedola/commits/master/MD/linkrels.md is (sort of 
a) history and i'd like to make that a little prettier than just a 
generic github commit log, but at least there is an open record of when 
and how values were changed.

**Comment by mnot** [comment]
See above. Re: discussion and history, that'll be a separate thing.

**Comment by timbl** [comment]
"I think it's reasonable to assume that IANA will product exactly one non-HTML format, and that will be XML; this is what they do for other registries, and we shouldn't expect a unicorn."
IANA took a look time to move to HTML and is still clearly suspicious of it.   We still have an obligation to lead them into more powerful formats, as in text > HTML and XML > turtle.  
Plus, when this stuff is used by the RDF community to not have the properties we use dereferenceable  on the web suggests we use use full URI which is in a domain where the rdf community can make sure that it works.   Or we can hack every single client code to have a magic redirect from the iana namespace to another domain under the covers.

**Comment by dret** [comment]
On 2016-02-05 08:53, Tim Berners-Lee wrote:
> Plus, when this stuff is used by the RDF community to not have the
> properties we use dereferenceable on the web suggests we use use full
> URI which is in a domain where the rdf community can make sure that it
> works. Or we can hack every single client code to have a magic redirect
> from the iana namespace to another domain under the covers.

the thing is that rather few registries have namespaces that are or even 
could be URIs. and like @mnot mentioned, we shouldn't expect a unicorn.

many registries have namespaces that cannot be URIs even if you wanted 
because their context requires them to be 16bit numbers or something 
similarly constrained.

i am working on a draft looking at the use of registries from many 
possible angles, and the identifier namespace of course is an important one.

https://tools.ietf.org/html/draft-wilde-registries-01#section-3.4

so while i think it is impossible to strive for IANA registries to 
*always use* URIs as registered values (it would be interesting to know 
how many of the existing 1'903 registries at least in theory could use 
URIs as their namespace), it may make sense to say that the registry 
entries should *have URIs*, thus making it possible to link to a 
registry entry when referring to it.

this would require some management effort in order to assign and use 
local identifiers for each submitted value. it's not hard to do, but it 
needs to be done and implemented robustly. also, registry users must be 
educated to understand the difference between a value's URI, and the 
actual value.

for example, it is clear that TCP port 80 never can be changed as a 
registered value to *be* a URI. but it would be useful for it to be 
better referencable on the web than having to manually page to this URI 
to find the value:

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=2

instead, it would be possible to either use the value as part of the URI 
(but this would be brittle and may break as a scheme if there are 
registries keeping history and doing reassignments), or to simply assign 
random "entry keys" and keep those stable.

for example, the following entry key could be used as a stable link to 
the port 80 entry:

http://www.iana.org/assignments/service-names-port-numbers#2387642

but this would very likely require a change to RFC 7500, which of course 
is a much bigger effort than revising RFC 5988.

**Comment by mnot** [comment]
From my chats with IANA staff, I think they'd consider hosting other formats, providing they were clearly specified and either produced for them, or reasonable for them to produce (e.g., with an XSLT transform). 

Would need to confirm this, of course, but if we had a proposal we could take it to them. One of the questions they'll ask is how much traffic we'd expect such things to get.

**Comment by dret** [comment]
On 2016-02-05 17:32, Mark Nottingham wrote:
> Would need to confirm this, of course, but if we had a proposal we could
> take it to them. One of the questions they'll ask is how much traffic
> we'd expect such things to get.

https://tools.ietf.org/html/draft-wilde-registries-01#section-5.6 tries 
to address this issue. if the model is that any implementation can and 
will get registry contents at runtime, then this can be very hard to 
scale up. currently, the pattern is that *developers* look at the 
registry, not their code at runtime. that's a very different thing.

**Comment by elf-pavlik** [comment]
maybe schema.org crew has some experience here to share? in mailing list conversation below @danbri @mfhepp @gkellogg and others discuss this issue, even referencing post about W3C’s Excessive DTD Traffic

* https://lists.w3.org/Archives/Public/public-vocabs/2014Jan/0035.html
* https://www.w3.org/blog/systeam/2008/02/08/w3c_s_excessive_dtd_traffic/

**Comment by asbjornu** [comment]
@elf-pavlik Your comment seems related to dret/I-D#21 and not so much this discussion. :) But yea, [schema.org](http://schema.org/) should have plenty of experience to share.

**Comment by danbri** [comment]
I would like to investigate the load on schema.org, however I didn't yet figure out whether Google AppEngine's generic logging can easily tell us about homepage requests that ask for application/ld+json. Expert advice on that would be welcomed; if nobody here happens to know I can ask around within Google of course, or even(!) revisit the documentation. Presumably there are probably also custom logging python APIs in appengine. /cc @RichardWallis

**Comment by dret** [comment]
On 2016-02-19 14:14, Dan Brickley wrote:
> I would like to investigate the load on schema.org, however I didn't yet
> figure out whether Google AppEngine's generic logging can easily tell us
> about homepage requests that ask for application/ld+json. Expert advice
> on that would be welcomed; if nobody here happens to know I can ask
> around within Google of course, or even(!) revisit the documentation.
> Presumably there are probably also custom logging python APIs in
> appengine. /cc @RichardWallis <https://github.com/RichardWallis>

it definitely would be great to hear more about what is happening and 
how much load it is.

in this case it hit a company that has among the world's best people and 
computing/network resources to handle this. it all depends on how a 
spec, its vocabulary, and the registry are supposed to be used. i still 
think that in most cases, the general model is that runtime access is a 
Bad Idea, and for whoever is hosting the registry, this can make a big 
difference. definitely something to keep in mind when considering how to 
split a spec into static and evolvable parts.

https://tools.ietf.org/html/draft-wilde-registries-01#section-5.5

**Comment by gkellogg** [comment]
We discussed this some time ago. I believe the best practice for an implementation is to cache retrieved contexts and reuse between successive requests. Ideally, the context is served with reasonable cache control directives. The Ruby JSON-LD processor does runtime caching of retrieved contexts.
