### ISSUE TITLE
Off by one?

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#183]
> Let N be the count of `URLs`' members, rounded up to power of 2.  If N is greater than 2\*\*32, then let N be 2\*\*31.

I think that should be "If N is greater than 2**31"...

**Comment by kazuho** [comment]
I believe it should be changed to: Round down N to power of 2, smaller than 2**32.

By changing as such, it would match the definition of P. It also makes the definition clear since log2(N) always becomes an integer.

(originally responded [here](https://github.com/mnot/I-D/issues/181#issuecomment-222612861) - link added to avoid confusion)
