### ISSUE TITLE
Clarifty "/foo/.well-known/example"

### ISSUE THREAD

**Issue by fluffy** [mnot/I-D#272]
Are you saying that URI MUST NOT have something like "/foo/.well-known/example" or are you saying that if they do then it can't be treated as a well known and it is just a name like any other. 

If you saying the first, that's nuts, people already have too much code that allows any name. If the later, then sure, but that seem to already come from where we say the .well-known has to be at the start of the path.

**Comment by mnot** [comment]
Do you mean a URI being created by a standard, or any URI?

**Comment by fluffy** [comment]
Is this like British or American sparrow ? Heck, I have no idea. Lets say an example URI in a standards that is not a well know one.

**Comment by mnot** [comment]
Putting it in an example would be just plain confusing, so that's not something a standard should do.

A standard specifying .well-known elsewhere in the path is specifically violating both this spec and BCP190.

A random Web server that decides to use such a path can of course do so -- but if they think it means something, they might be disappointed.

**Comment by fluffy** [comment]
Make sense ... so I did not get that reading this so might need a bit of a tweak.

**Comment by mnot** [comment]
Will see what I can do.
