### ISSUE TITLE
Parameter ABNF

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#33]
See:
  http://www.rfc-editor.org/errata_search.php?rfc=5988&eid=3158

**Comment by prushforth** [comment]
I entered a (rejected) erratum on the subject of the acceptable syntax for the media type parameter, here: http://www.rfc-editor.org/errata_search.php?rfc=5988 , number 4344.  I believe the discussion relating to the basis for rejecting my suggestion is in this thread:
https://lists.w3.org/Archives/Public/ietf-http-wg/2010JanMar/0153.html

Hopefully a resolution can be found by allowing media type parameters in quoted-mt values - otherwise I can see the "=" and ";" characters causing parser issues.

Thanks

**Comment by mnot** [comment]
@reschke ping

**Comment by mnot** [comment]
@reschke ping?

**Comment by reschke** [comment]
So this is not super-easy due to how the spec is structured, and because making things generic is indeed breaking a few edge cases. I'd start with something like:


# Link Serialisation in HTTP Headers {#header}

The Link header field provides a means for serialising one or more links into HTTP headers.

The ABNF for the field value is given below:

~~~ abnf2616
	Link           = #link-value
	link-value     = "<" URI-Reference ">" OWS *( OWS ";" OWS link-param )
  link-param     = token "=" ( token / quoted-string )
~~~

This specification defines the parameters "rel", "anchor", "rev", "hreflang",
"media", "title", "title*", and "type".
  
ABNF for "rel" and "rev" parameter values:

~~~ abnf2616
	rel            = relation-typ *( 1*SP relation-type )
	rev            = relation-typ *( 1*SP relation-type )

	relation-type  = reg-rel-type | ext-rel-type
	reg-rel-type   = LOALPHA *( LOALPHA | DIGIT | "." | "-" )
	ext-rel-type   = URI
~~~~

ABNF for "anchor" parameter:
~~~ abnf2616
  anchor         = URI-Reference
~~~

ABNF for "hreflang" parameter:
~~~ abnf2616
  hreflang       = Language-Tag
~~~
  
ABNF for "media" parameter:
~~~ abnf2616
  media          = media_query_list
~~~

ABNF for "type" parameter:
~~~ abnf2616
	type           = media-type
~~~

TODO:

- integrate value ABNFs into parameter descriptions
- explains what's changed by making things generic: (1) certain things can appear as token, (2) where 5988 specified quotes, it failed to discuss quoted-string handling, (3) media-type by definition would need to be quoted, as "/" is not a token character

**Comment by mnot** [comment]
Seems reasonable to me, thanks. I'll integrate and ref this issue, but keep it open to make sure I get it right.

**Comment by mnot** [comment]
TODO:

* [ ] Change: certain things can appear as token
* [ ] Change: quoted string handling
* [ ] Change: media type needs to be quoted
* [ ] Specify `title` / `title*`
* [ ] import `media-type` or define it
* [ ] clean up imports (if necessary)
* [ ] integrate value ABNFs into parameter descriptions

**Comment by mnot** [comment]
@reschke thanks. You going to take a stab at `title` / `title*`, or wait for #180?

**Comment by reschke** [comment]
well, the title value doesn't have an ABNF, for title* we can of course refer to rfc5987bis.

**Comment by mnot** [comment]
~~~
  title  = ( token / quoted-string )
  title* = ext-value
~~~

with an appropriate import? 

Can an ABNF rule name include "*"?

Also, 5987bis allows LWSP around `=` -- what about here (and on other link params)?

**Comment by reschke** [comment]
No; the param value ABNF should describe the syntax *after* undoing quoted-string, thus for title there's no structure left to enforce.

For "title*", ext-value is correct.

ABNF rule names can not have "*", so maybe use "title-star".

RFC5987bis doesn't contain this (ABNF about anything except ext-value) anymore. So it's up to the spec that uses the notation. Whether WSP around "=" is allowed varies a lot for the existing header fields. The best approach probably is to say "BWS" (-> <https://greenbytes.de/tech/webdav/rfc7230.html#rule.whitespace>)

**Comment by mnot** [comment]
I see. Will have a go.

**Comment by reschke** [comment]
FWIW, have a look at how we describe the syntax of cache-control directive values in RFC 7234...

**Comment by mnot** [comment]
@reschke have a look. Still need to talk about 5987 encoding.

**Comment by mnot** [comment]
@reschke currently:

> "<" URI-Reference ">" OWS *( OWS ";" OWS link-param )

Is the first `OWS` really necessary?

Also, thinking about putting BWS around URI-Reference.

**Comment by reschke** [comment]
1) No, it's not.

2) BWS in front of doesn't make sense; leading whitespace is already consumed by parsing the message into field-name/field-value pairs (see <https://greenbytes.de/tech/webdav/rfc7230.html#header.fields>: "header-field   = field-name ":" OWS field-value OWS").

**Comment by mnot** [comment]
I mean 

> "<" BWS URI-Reference BWS ">"

**Comment by reschke** [comment]
No, that looks like a really bad idea to me. Have you seen that in the wild?

**Comment by mnot** [comment]
Not as such, but I suspect consumers will want to treat it leniently. Why does it look bad? Semantics seem clear...

**Comment by reschke** [comment]
Well, putting things into "<" and ">" to me is quoting mechanism. Would you also say that "a" and " a " are equivalent?

**Comment by mnot** [comment]
As URLs, yes. Remember, it's BWS.

**Comment by reschke** [comment]
Well, I just wrote code that uses the Link header field, based on RFC 5987. And it would break if the sender would add whitespace around the brackets. The proposed change IMHO violates the <https://de.wikipedia.org/wiki/Principle_of_Least_Surprise> (while allowing whitespace around "=" does not...)

**Comment by mnot** [comment]
RFC5987 is an Implied LWS spec, and "<" ">" are separators. Your new code is too strict.

**Comment by reschke** [comment]
They are in the RFC 2616 grammar, but in the Link header field they are used as quote characters, not separators.

**Comment by mnot** [comment]
[Hmm](https://www.youtube.com/watch?v=ae8t-QKPVY4). OK.

**Comment by reschke** [comment]
Further notes:

- "_" is not legal in a production name
- use "/" instead of "|"
